### ISSUE TITLE
Error on lanuch with 3.3.3

### ISSUE THREAD

**Issue by jhughes-dev** [juliand665/Dynamic-FPS#156]
I see this message when I launch with 3.3.3. Only I cannot find any such mod. 

```
Incompatible mods found!
net.fabricmc.loader.impl.FormattedException: Some of your mods are incompatible with the game or each other!
A potential solution has been determined, this may resolve your problem:
	 - Replace mod 'MixinExtras' (mixinextras) 0.3.1 with version 0.3.2 or later.
More details:
	 - Mod 'Dynamic FPS' (dynamic_fps) 3.3.3 requires version 0.3.2 or later of mod 'MixinExtras' (mixinextras), but only the wrong version is present: 0.3.1!
	at net.fabricmc.loader.impl.FormattedException.ofLocalized(FormattedException.java:51)
	at net.fabricmc.loader.impl.FabricLoaderImpl.load(FabricLoaderImpl.java:195)
	at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:146)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:68)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
```

**Comment by LostLuma** [comment]
You will need to upgrade your Fabric / Quilt Loader to version 0.15.0 / 0.23.0 (or above), both ship MixinExtras 0.3.2.
