### ISSUE TITLE
Whats MixinExtras

### ISSUE THREAD

**Issue by PesarShah** [juliand665/Dynamic-FPS#178]
Error : **Incompatible mods found!
net.fabricmc.loader.impl.FormattedException: Some of your mods are incompatible with the game or each other!
A potential solution has been determined, this may resolve your problem:
	 - Replace mod 'MixinExtras' (mixinextras) 0.3.0 with version 0.3.2 or later.
More details:
	 - Mod 'Dynamic FPS' (dynamic_fps) 3.4.2 requires version 0.3.2 or later of mod 'MixinExtras' (mixinextras), but only the wrong version is present: 0.3.0!
	at net.fabricmc.loader.impl.FormattedException.ofLocalized(FormattedException.java:51)
	at net.fabricmc.loader.impl.FabricLoaderImpl.load(FabricLoaderImpl.java:195)
	at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:146)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:68)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
** Pls Help Me To fix

**Comment by LostLuma** [comment]
Hello, [MixinExtras](https://github.com/LlamaLad7/MixinExtras) is a library that helps mod developers write more compatible code. Fabric Loader recently started including this library, which is why we started making use of it. You'll want to upgrade to Fabric Loader `0.15.2` or later (preferably simply use the newest version) and then you're good to go.
