### ISSUE TITLE
Unexpected CME error (crash)

### ISSUE THREAD

**Issue by VidTu** [juliand665/Dynamic-FPS#220]
## Description

Happened when I ALT+TABbed out of the game.

## Versions

Minecraft: 1.21.1
OS: Windows 11 Enterprise x64
Fabric Loader: 0.16.5
Fabric API: 0.103.0+1.21.1
Java: Azul Zulu JDK 21.0.4 x64
Launcher: PrismLauncher 8.4
DynamicFPS: 3.6.3

## Stack-trace

I can DM you the full crash-report in the Discord if you need it.

```
java.util.ConcurrentModificationException
	at java.base@21.0.4/java.util.HashMap.forEach(HashMap.java:1432)
	at MC//net.minecraft.client.sound.SoundSystem.dynamic_fps$updateVolume(SoundSystem.java:1672)
	at dynamic_fps.impl.feature.volume.SmoothVolumeHandler.updateVolume(SmoothVolumeHandler.java:80)
	at dynamic_fps.impl.feature.volume.SmoothVolumeHandler.tickVolumes(SmoothVolumeHandler.java:69)
	at net.lostluma.dynamic_fps.impl.textile.service.TextilePlatform.lambda$registerStartTickEvent$0(TextilePlatform.java:61)
	at net.fabricmc.fabric.api.client.event.lifecycle.v1.ClientTickEvents.lambda$static$0(ClientTickEvents.java:34)
	at MC//net.minecraft.client.MinecraftClient.handler$bld000$fabric-lifecycle-events-v1$onStartTick(MinecraftClient.java:10178)
	at MC//net.minecraft.client.MinecraftClient.tick(MinecraftClient.java)
	at MC//net.minecraft.client.MinecraftClient.render(MinecraftClient.java:1246)
	at MC//net.minecraft.client.MinecraftClient.run(MinecraftClient.java:882)
	at net.minecraft.client.main.Main.main(Main.java:256)
	at app//net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:480)
	at app//net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at app//net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
	at app//org.prismlauncher.launcher.impl.StandardLauncher.launch(StandardLauncher.java:100)
	at app//org.prismlauncher.EntryPoint.listen(EntryPoint.java:129)
	at app//org.prismlauncher.EntryPoint.main(EntryPoint.java:70)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at java.base@21.0.4/java.util.HashMap.forEach(HashMap.java:1432)
	at MC//net.minecraft.client.sound.SoundSystem.dynamic_fps$updateVolume(SoundSystem.java:1672)
	at dynamic_fps.impl.feature.volume.SmoothVolumeHandler.updateVolume(SmoothVolumeHandler.java:80)
	at dynamic_fps.impl.feature.volume.SmoothVolumeHandler.tickVolumes(SmoothVolumeHandler.java:69)
	at net.lostluma.dynamic_fps.impl.textile.service.TextilePlatform.lambda$registerStartTickEvent$0(TextilePlatform.java:61)
	at net.fabricmc.fabric.api.client.event.lifecycle.v1.ClientTickEvents.lambda$static$0(ClientTickEvents.java:34)
	at MC//net.minecraft.client.MinecraftClient.handler$bld000$fabric-lifecycle-events-v1$onStartTick(MinecraftClient.java:10178)
Mixins in Stacktrace: None found

-- Uptime --
Details:
	JVM uptime: 10640.242s
	Wall uptime: 10601.260s
	High-res time: 74200.600s
	Client ticks: 211134 ticks / 10556.700s
Stacktrace:
	at MC//net.minecraft.client.MinecraftClient.addDetailsToCrashReport(MinecraftClient.java:2501)
	at MC//net.minecraft.client.MinecraftClient.printCrashReport(MinecraftClient.java:949)
	at MC//net.minecraft.client.MinecraftClient.run(MinecraftClient.java:905)
	at net.minecraft.client.main.Main.main(Main.java:256)
	at app//net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:480)
	at app//net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at app//net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
	at app//org.prismlauncher.launcher.impl.StandardLauncher.launch(StandardLauncher.java:100)
	at app//org.prismlauncher.EntryPoint.listen(EntryPoint.java:129)
	at app//org.prismlauncher.EntryPoint.main(EntryPoint.java:70)
Mixins in Stacktrace: None found
```

## Config

```json
{
  "uncap_menu_frame_rate": true,
  "idle": {
    "condition": "none"
  },
  "battery_tracker": {
    "notifications": false,
    "display": {
      "condition": "disabled"
    }
  },
  "download_natives": false,
  "states": {
    "unfocused": {
      "frame_rate_target": 30,
      "volume_multipliers": {
        "master": 1.0
      },
      "graphics_state": "reduced",
      "show_toasts": true
    },
    "invisible": {
      "volume_multipliers": {
        "music": 0.0,
        "record": 0.0,
        "weather": 0.0,
        "block": 0.0,
        "hostile": 0.0,
        "neutral": 0.0,
        "player": 0.0,
        "ambient": 0.0,
        "voice": 0.0
      },
      "graphics_state": "minimal",
      "run_garbage_collector": true
    },
    "unplugged": {
      "enable_vsync": false
    },
    "abandoned": {
      "frame_rate_target": 0,
      "volume_multipliers": {
        "master": 0.0,
        "music": 0.0,
        "record": 0.0,
        "weather": 0.0,
        "block": 0.0,
        "hostile": 0.0,
        "neutral": 0.0,
        "player": 0.0,
        "ambient": 0.0,
        "voice": 0.0
      },
      "graphics_state": "minimal",
      "run_garbage_collector": true
    }
  }
}
```

**Comment by LostLuma** [comment]
Interesting! Are you using any other mods besides the ones mentioned in your report?

**Comment by VidTu** [comment]
yes, i'm using lots of mods, so it might be hard to pinpoint the issue if this is a mod conflict, however it was a one-blow crash, probably a race, i.e. it doesn't crash like that every time, and, in fact, it was the first crash in one month or so.

nevertheless, the mods are:
```
		accelerateddecay: Accelerated Decay 21.0.0
		advancementsscreenoptimizer: AdvancementsScreenOptimizer 1.0.0+1.21
		alternate-current: Alternate Current 1.9.0
		appleskin: AppleSkin 3.0.5+mc1.21
		architectury: Architectury 13.0.6
		async-pack-scan: Async Pack Scan 0.2.5
		audioshutdown: AudioShutdown 2.0
		badhorsefix: Bad Horse Fix 2.0.0-fabric
		badoptimizations: BadOptimizations 2.1.4
		balm-fabric: Balm 21.0.19
			kuma_api: KumaAPI 21.0.5-SNAPSHOT
		better-pie-chart: Better Pie Chart 1.0.0+1.20
		betteradvancements: Better Advancements 0.4.2.19
		betterbeds: Better Beds 1.4.0
		bettercommandblockui: BetterCommandBlockUI 0.5.2a
		bettermounthud: Better Mount HUD 1.2.4
		betternightvision: Better Night Vision 1.0.0
		betterstats: Better Statistics Screen 3.13.2+fabric-1.21
		blockmeter: Block Meter 1.14
		c2me: Concurrent Chunk Management Engine 0.3.0+alpha.0.206+1.21.1
			c2me-base: Concurrent Chunk Management Engine (Base) 0.3.0+alpha.0.206+1.21.1
			c2me-client-uncapvd: Concurrent Chunk Management Engine (Client/Uncap View Distance) 0.3.0+alpha.0.206+1.21.1
			c2me-fixes-chunkio-threading-issues: Concurrent Chunk Management Engine (Fixes/Chunk IO/Threading Issues) 0.3.0+alpha.0.206+1.21.1
			c2me-fixes-general-threading-issues: Concurrent Chunk Management Engine (Fixes/General/Threading Issues) 0.3.0+alpha.0.206+1.21.1
			c2me-fixes-worldgen-threading-issues: Concurrent Chunk Management Engine (Fixes/WorldGen/Threading Issues) 0.3.0+alpha.0.206+1.21.1
			c2me-fixes-worldgen-vanilla-bugs: Concurrent Chunk Management Engine (Fixes/WorldGen/Vanilla Bugs) 0.3.0+alpha.0.206+1.21.1
			c2me-notickvd: Concurrent Chunk Management Engine (No Tick View Distance) 0.3.0+alpha.0.206+1.21.1
			c2me-opts-allocs: Concurrent Chunk Management Engine (Optimizations/Memory Allocations) 0.3.0+alpha.0.206+1.21.1
			c2me-opts-chunk-access: Concurrent Chunk Management Engine (Optimizations/Chunk Access) 0.3.0+alpha.0.206+1.21.1
			c2me-opts-chunkio: Concurrent Chunk Management Engine (Optimizations/Chunk IO) 0.3.0+alpha.0.206+1.21.1
			c2me-opts-math: Concurrent Chunk Management Engine (Optimizations/Math) 0.3.0+alpha.0.206+1.21.1
			c2me-opts-scheduling: Concurrent Chunk Management Engine (Optimizations/Scheduling) 0.3.0+alpha.0.206+1.21.1
			c2me-opts-worldgen-general: Concurrent Chunk Management Engine (Optimizations/General WorldGen) 0.3.0+alpha.0.206+1.21.1
			c2me-opts-worldgen-vanilla: Concurrent Chunk Management Engine (Optimizations/Vanilla WorldGen) 0.3.0+alpha.0.206+1.21.1
			c2me-rewrites-chunk-serializer: Concurrent Chunk Management Engine (Rewrites/Chunk Serializer) 0.3.0+alpha.0.206+1.21.1
			c2me-rewrites-chunk-system: Concurrent Chunk Management Engine (Rewrites/Chunk System) 0.3.0+alpha.0.206+1.21.1
			c2me-rewrites-chunkio: Concurrent Chunk Management Engine (Rewrites/Chunk IO) 0.3.0+alpha.0.206+1.21.1
			c2me-server-utils: Concurrent Chunk Management Engine (Server Utils) 0.3.0+alpha.0.206+1.21.1
			c2me-threading-lighting: Concurrent Chunk Management Engine (Threading/Lighting) 0.3.0+alpha.0.206+1.21.1
			com_ibm_async_asyncutil: asyncutil 0.1.0
			io_reactivex_rxjava3_rxjava: rxjava 3.1.8
			mixinsquared: MixinSquared 0.2.0-beta.6
			net_objecthunter_exp4j: exp4j 0.4.8
			org_jctools_jctools-core: jctools-core 4.0.5
			org_reactivestreams_reactive-streams: reactive-streams 1.0.4
		calcmod: CalcMod 1.3.2+fabric.1.21
			clientarguments: clientarguments 1.9
			org_mariuszgromada_math_mathparser_org-mxparser: MathParser.org-mXparser 5.0.6
		capes: Capes 1.5.4+1.21
		cat_jam: cat_jam 1.2.3
		centered-crosshair: Centered Crosshair 1.0.8
		chat_heads: Chat Heads 0.12.10
		chatnotify: ChatNotify 2.1.0-beta.4
		chesttracker: Chest Tracker 2.5.2+1.21.1
			searchables: Searchables 1.0.1
		cicada: CICADA 0.8.3+1.21-and-above
		clean-debug: Clean F3 0.4.6
		clientcommands: Client Commands 2.9.1
			betterconfig: BetterConfig 1.3
		clientsort: ClientSort 0.9.0
		cloth-config: Cloth Config v15 15.0.130
			cloth-basic-math: cloth-basic-math 0.6.1
		clumps: Clumps 19.0.0.1
		collisionfix: CollisionFix 1.0.1
		completeconfig: CompleteConfig 2.5.4
			completeconfig-base: completeconfig-base 2.5.4
			completeconfig-gui-cloth: completeconfig-gui-cloth 2.5.4
			completeconfig-gui-yacl: completeconfig-gui-yacl 2.5.4
		crosshairtweaks: Crosshair Tweaks 1.2.0
		cullparticles: Cull Particles 1.1-1.21
		customclientbrand: Custom Client Brand 1.0.1+1.20.5
		detailab: Detail Armor Bar 2.6.3+1.21.1-fabric
		disableaccessibilityscreen: DisableAccessibilityScreen 1.0.1
		disableportalchecks: DisablePortalChecks 1.0.0
		droppeditemtweaks: Dropped Item Tweaks 1.1.0
		dynamic_fps: Dynamic FPS 3.6.3
			net_lostluma_battery: battery 1.1.0
		e4mc_minecraft: e4mc 5.1.0
			folk_sisby_kaleido-config: kaleido-config 0.3.1+1.3.1
		eatinganimationid: Eating Animation 1.21+1.9.72
		emojitype: Emoji Type 2.2.7-1.21.1
		enhanced_attack_indicator: Enhanced Attack Indicator 1.0.4+1.21
		enhancedblockentities: Enhanced Block Entities 0.10.1+1.21
		enhancedpacketcompression: EnhancedPacketCompression 0.0.2-Beta+1.20.2
		entityculling: EntityCulling 1.7.0
		f3teverywhere: F3+T Everywhere 1.0.1
		fabric-api: Fabric API 0.103.0+1.21.1
			fabric-api-base: Fabric API Base 0.4.42+6573ed8c19
			fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.6.68+b559734419
			fabric-biome-api-v1: Fabric Biome API (v1) 13.0.29+5bd9f1bc19
			fabric-block-api-v1: Fabric Block API (v1) 1.0.22+0af3f5a719
			fabric-block-view-api-v2: Fabric BlockView API (v2) 1.0.10+6573ed8c19
			fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.52+0af3f5a719
			fabric-client-tags-api-v1: Fabric Client Tags 1.1.15+6573ed8c19
			fabric-command-api-v1: Fabric Command API (v1) 1.2.49+f71b366f19
			fabric-command-api-v2: Fabric Command API (v2) 2.2.28+6ced4dd919
			fabric-commands-v0: Fabric Commands (v0) 0.2.66+df3654b319
			fabric-content-registries-v0: Fabric Content Registries (v0) 8.0.16+b559734419
			fabric-convention-tags-v1: Fabric Convention Tags 2.0.21+7f945d5b19
			fabric-convention-tags-v2: Fabric Convention Tags (v2) 2.6.1+9b16164119
			fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.2.29+0af3f5a719
			fabric-data-attachment-api-v1: Fabric Data Attachment API (v1) 1.1.28+1daea21519
			fabric-data-generation-api-v1: Fabric Data Generation API (v1) 20.2.18+16c4ae2519
			fabric-dimensions-v1: Fabric Dimensions API (v1) 4.0.0+6fc22b9919
			fabric-entity-events-v1: Fabric Entity Events (v1) 1.7.0+2122d82819
			fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.7.12+ba9dae0619
			fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.53+6ced4dd919
			fabric-item-api-v1: Fabric Item API (v1) 11.0.0+afdfc92119
			fabric-item-group-api-v1: Fabric Item Group API (v1) 4.1.5+3fc0e55219
			fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.47+0af3f5a719
			fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.45+df3654b319
			fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 2.3.12+6c1df36019
			fabric-loot-api-v2: Fabric Loot API (v2) 3.0.14+3f89f5a519
			fabric-loot-api-v3: Fabric Loot API (v3) 1.0.2+3f89f5a519
			fabric-message-api-v1: Fabric Message API (v1) 6.0.13+6573ed8c19
			fabric-model-loading-api-v1: Fabric Model Loading API (v1) 2.0.0+fe474d6b19
			fabric-networking-api-v1: Fabric Networking API (v1) 4.2.2+60c3209b19
			fabric-object-builder-api-v1: Fabric Object Builder API (v1) 15.2.0+40875a9319
			fabric-particles-v1: Fabric Particles (v1) 4.0.2+6573ed8c19
			fabric-recipe-api-v1: Fabric Recipe API (v1) 5.0.12+6508971219
			fabric-registry-sync-v0: Fabric Registry Sync (v0) 5.1.2+60c3209b19
			fabric-renderer-api-v1: Fabric Renderer API (v1) 3.4.0+c705a49c19
			fabric-renderer-indigo: Fabric Renderer - Indigo 1.7.0+c705a49c19
			fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 3.2.68+df3654b319
			fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.3.48+73761d2e19
			fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 3.1.6+1daea21519
			fabric-rendering-v0: Fabric Rendering (v0) 1.1.71+df3654b319
			fabric-rendering-v1: Fabric Rendering (v1) 5.0.5+df16efd019
			fabric-resource-conditions-api-v1: Fabric Resource Conditions API (v1) 4.3.0+8dc279b119
			fabric-resource-loader-v0: Fabric Resource Loader (v0) 1.3.0+5659912919
			fabric-screen-api-v1: Fabric Screen API (v1) 2.0.25+8b68f1c719
			fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.3.86+b559734419
			fabric-sound-api-v1: Fabric Sound API (v1) 1.0.23+6573ed8c19
			fabric-transfer-api-v1: Fabric Transfer API (v1) 5.1.17+1db1cc1f19
			fabric-transitive-access-wideners-v1: Fabric Transitive Access Wideners (v1) 6.1.0+1daea21519
		fabric-language-kotlin: Fabric Language Kotlin 1.12.1+kotlin.2.0.20
			org_jetbrains_kotlin_kotlin-reflect: kotlin-reflect 2.0.20
			org_jetbrains_kotlin_kotlin-stdlib: kotlin-stdlib 2.0.20
			org_jetbrains_kotlin_kotlin-stdlib-jdk7: kotlin-stdlib-jdk7 2.0.20
			org_jetbrains_kotlin_kotlin-stdlib-jdk8: kotlin-stdlib-jdk8 2.0.20
			org_jetbrains_kotlinx_atomicfu-jvm: atomicfu-jvm 0.25.0
			org_jetbrains_kotlinx_kotlinx-coroutines-core-jvm: kotlinx-coroutines-core-jvm 1.8.1
			org_jetbrains_kotlinx_kotlinx-coroutines-jdk8: kotlinx-coroutines-jdk8 1.8.1
			org_jetbrains_kotlinx_kotlinx-datetime-jvm: kotlinx-datetime-jvm 0.6.1
			org_jetbrains_kotlinx_kotlinx-io-bytestring-jvm: kotlinx-io-bytestring-jvm 0.5.3
			org_jetbrains_kotlinx_kotlinx-io-core-jvm: kotlinx-io-core-jvm 0.5.3
			org_jetbrains_kotlinx_kotlinx-serialization-cbor-jvm: kotlinx-serialization-cbor-jvm 1.7.1
			org_jetbrains_kotlinx_kotlinx-serialization-core-jvm: kotlinx-serialization-core-jvm 1.7.1
			org_jetbrains_kotlinx_kotlinx-serialization-json-jvm: kotlinx-serialization-json-jvm 1.7.1
		fabricloader: Fabric Loader 0.16.5
			mixinextras: MixinExtras 0.4.1
		fadeless: Fadeless 1.1.0
		fast-recipe: Fast Recipe 1.0.0+1.20.5-1.21
		faster-random: Faster Random 5.1.0
		fastipping: Fast IP Ping 1.0.4
		fastitems: Fast Items 1.0.0-1.21
		fastquit: FastQuit 3.0.0+1.20.6
		fasttrading: Fast Trading 0.1.5+1.21
		ferritecore: FerriteCore 7.0.0
		feytweaks: FeyTweaks 1.21-1.2.8
		fishingrodfix: Fishing rod fix 1.21-0.3
		fix-mc-stats: FixMCStats 1.1.0
		fixbookgui: Fix Book Gui 1.7.0
		forcecloseworldloadingscreen: kennytv's epic force close loading screen mod for Fabric 2.2.2
		forgeconfigapiport: Forge Config API Port 21.1.0
			com_electronwill_night-config_core: core 3.8.0
			com_electronwill_night-config_toml: toml 3.8.0
		freecam: Freecam 1.3.0+mc1.21
		fullstackwatchdog: FullStack Watchdog 1.0.1+1.19.2-fabric
		fzzy_config: Fzzy Config 0.4.1+1.21
			blue_endless_jankson: jankson 1.2.3
			fabric-permissions-api-v0: fabric-permissions-api 0.3.1
			net_peanuuutz_tomlkt_tomlkt-jvm: tomlkt-jvm 0.3.7
		gammautils: Gamma Utils 2.1.0
		healthindicators: Health Indicators 21.1.1
		hopperhedgehog: Hopper The Hedgehog 2.1.0-1.20.5
		ias: In-Game Account Switcher 9.0.2-SNAPSHOT
		immediatelyfast: ImmediatelyFast 1.2.21+1.21.1
			net_lenni0451_reflect: Reflect 1.3.4
		inventory_control_tweaks: Inventory Control Tweaks 1.4.1
		inventory_tabs: Inventory Tabs 1.4.0+1.21
		inventoryessentials: Inventory Essentials 21.1.1
		iris: Iris 1.8.0-beta.3+mc1.21.1
			io_github_douira_glsl-transformer: glsl-transformer 2.0.1
			org_anarres_jcpp: jcpp 1.4.14
			org_antlr_antlr4-runtime: antlr4-runtime 4.13.1
		itemswapper: ItemSwapper 0.7.1
		jade: Jade 15.3.4+fabric
		java: OpenJDK 64-Bit Server VM 21
		krypton: Krypton 0.2.8
			com_velocitypowered_velocity-native: velocity-native 3.3.0-SNAPSHOT
		ksyxis: Ksyxis 1.3.2
		lazy-language-loader: lazy-language-loader 0.3.7
		letmedespawn: Let Me Despawn 1.3.1
		libjf: LibJF 3.17.0
			libjf-base: LibJF Base 3.17.0
			libjf-config-commands: LibJF Config Commands 3.17.0
			libjf-config-core-v2: LibJF Config 3.17.0
			libjf-config-network-v0: LibJF Config: Network 3.17.0
			libjf-config-ui-tiny: LibJF Config UI: Tiny 3.17.0
			libjf-data-manipulation-v0: LibJF Data Manipulation 3.17.0
			libjf-data-v0: LibJF Data 3.17.0
			libjf-mainhttp-v0: LibJF MainHTTP 3.17.0
			libjf-resource-pack-entry-widgets-v0: LibJF Resource Pack Entry Widgets 3.17.0
			libjf-translate-v1: LibJF Translate 3.17.0
			libjf-unsafe-v0: LibJF Unsafe 3.17.0
			libjf-web-v1: LibJF Web 3.17.0
		lighty: Lighty 3.0.0-beta.4
		listentryhighlightfix: List Entry Highlight Fix 1.0.0
		litematica: Litematica 0.19.50
		litematica_printer: Litematica Printer 7.2.1
		lithium: Lithium 0.13.0
		logarithmic-volume-control: Logarithmic Volume Control 1.0.0-1.21
		malilib: MaLiLib 0.21.0
		methane: Methane 3.8.2
			libmcdev-fabric: libmcdev-fabric 1.4.2
		midnightlib: MidnightLib 1.6.3
		minecraft: Minecraft 1.21.1
		mixintrace: MixinTrace 1.1.1+1.17
		modelfix: Model Gap Fix 1.21-1.6
		modernfix: ModernFix 5.19.3+mc1.21.1
		modmenu: Mod Menu 11.0.2
		morechathistory: More Chat History 1.3.1
		moreculling: More Culling 0.27.1
			com_github_fallen-breath_conditional-mixin: conditional-mixin v0.6.2
		mountopacity: MountOpacity 1.0.0
		mousetweaks: Mouse Tweaks 2.26
		mr_aesthetic_andperformant: aesthetic and performant 1.5
		nametagtweaks: Nametag Tweaks 1.3.4
		narrus_yeetus: Narrus Yeetus 1.1.0
		nbt_ac: NBT Autocomplete 1.3.4
		no-resource-pack-warnings: No Resource Pack Warnings 1.3.0
		no-telemetry: No Telemetry 1.8.0
		nochatreports: No Chat Reports 1.21-v2.8.0
		noisium: Noisium 2.3.0+mc1.21-1.21.1
		nosigngui: NoSignGUI 1.0
		notenoughanimations: NotEnoughAnimations 1.7.6
		noweathereffects: No Weather Effects 1.7.0
		noxesium: Noxesium 2.3.0+3bbfed9
			com_noxcrew_noxesium_api: api 2.3.0+3bbfed9
			org_khelekore_prtree: prtree 1.5
		optipainting: OptiPainting 1.0.0+1.20.6
		overlaytweaks: Overlay Tweaks 1.10.0
			com_moulberry_mixinconstraints: mixinconstraints 1.0.1
		owo: oωo 0.12.12+1.21
			io_wispforest_endec: endec 0.1.5
			io_wispforest_endec_gson: gson 0.1.3
			io_wispforest_endec_jankson: jankson 0.1.3
			io_wispforest_endec_netty: netty 0.1.2
		paginatedadvancements: Paginated Advancements 2.5.1
		particle_core: Particle Core 0.2.4+1.21
			conditional-mixin: conditional mixin 0.5.1
		particletweaks: Particle Tweaks 1.2.1-mc1.21.1
		peek: Peek 1.21.1-1.3.5
		plasmovoice: Plasmo Voice 2.0.10
			aopalliance_aopalliance: aopalliance 1.0
			com_google_inject_guice: guice 5.0.1
			javax_inject_javax_inject: javax.inject 1
		potatoptimize: potatoptimize 0.0.1-dev.7
		rebind_all_the_keys: RebindAllTheKeys 1.5.2+1.21
		recipecooldown: Recipe Cooldown 1.17.1-1.0.0
		recursiveresources: Recursive Resources 2.5.3+1.21
			shared-resources-api: Shared Resources API 1.8.0
		reeses-sodium-options: Reese's Sodium Options 1.8.0-beta.2+mc1.21.1
		removewardeneffect: Remove Warden Darkness 0.0.2-1.20.6
		rendertweaks: Render Tweaks 1.1.0
		reset-keys-confirmation-screen: Reset Keys Confirmation Screen 1.3.0
		resourcepackchecker: Server Resource Pack Checker 1.21.1-1.2.2
		resourcify: Resourcify 1.4.1
			universalcraft: UniversalCraft 342
		ridehud: Ride Hud 1.3.4+1.21
		ridingmousefix: Riding Mouse Fix 1.0.1
		rrls: Remove Reloading Screen 5.0.7+mc1.21-fabric
		screenfx: ScreenFX 1.4.2+1.21
		screenshotclipboard: Screenshot to Clipboard 1.0.10
		screenshots: Screenshots 2.0.3
		seamless: Seamless 2.3.0
		servercore: ServerCore 1.5.5+1.21.1
			org_yaml_snakeyaml: snakeyaml 2.2
			placeholder-api: Placeholder API 2.4.1+1.21
			space_arim_dazzleconf_dazzleconf-core: dazzleconf-core 1.3.0-M2
			space_arim_dazzleconf_dazzleconf-ext-snakeyaml: dazzleconf-ext-snakeyaml 1.3.0-M2
		serverpingerfixer: Server Pinger Fixer 1.0.5
		shut_up_gl_error: Shut Up GL Error 1.0.0
		skinlayers3d: 3d-Skin-Layers 1.6.7
		skiptransitions: Skip Transitions 1.4.0+mc1.20.5
		smoothscroll: Smooth Scroll 2.1.3
		sodium: Sodium 0.6.0-beta.1+mc1.21
		sodium-extra: Sodium Extra 0.6.0-beta.1+mc1.21.1
			com_lodborg_interval-tree: interval-tree 1.0.0
		spark: spark 1.10.97
		stack-to-nearby-chests: Stack to Nearby Chests 0.5.8
		stackdeobfuscator: StackDeobfuscator 1.4.3+08e71cc
			net_fabricmc_mapping-io: mapping-io 0.6.1
			stackdeobfuscator-common: StackDeobfuscator Common 1.4.3+08e71cc
		status-effect-bars: Status Effect Bars 1.0.6
		statuseffecttimer: Status Effect Timer 1.2.0+1.21
		stutterfix: StutterFix mc1.21-0.2.3
		suppressopengl1280: Suppress OpenGL Errors 1.2.3
		tabtweaks: Tab Tweaks 1.3.3
		tcdcommons: TCD Commons API 3.12.3+fabric-1.21
		threadtweak: ThreadTweak 0.1.5+mc1.21.1
		threatengl: ThreatenGL 1.3.3-release.1
		titletweaks: Title Tweaks 1.1.2
		toomanyplayers: Too Many Players 1.21-1.1.5
			libgui: LibGui 11.1.0+1.21
				jankson: Jankson 8.0.0+j1.2.3
				libninepatch: LibNinePatch 1.2.0
		totemcounter: TotemCounter 1.6.1+mc1.21
		twd-sasf: ServerAddressSpaceFix 0.2.0
		tweakeroo: Tweakeroo 0.21.50
		ukulib: ukulib 1.4.0+1.21
			com_moandjiezana_toml_toml4j: toml4j 0.7.2
		ukus-armor-hud: uku's Armor HUD 0.5.1+mc1.21
		vanillaconfig: Vanilla Config 1.2.11+1.21
		viafabricplus: ViaFabricPlus 3.4.5
			com_google_code_findbugs_jsr305: jsr305 3.0.2
			com_vdurmont_semver4j: semver4j 3.1.0
			com_viaversion_viabackwards-common: viabackwards-common 5.0.4-20240820.141314-8
			com_viaversion_viaversion-common: viaversion-common 5.0.4-20240823.121229-16
			de_florianmichael_classic4j: Classic4J 2.0.2
			io_jsonwebtoken_jjwt-api: jjwt-api 0.12.6
			io_jsonwebtoken_jjwt-gson: jjwt-gson 0.12.6
			io_jsonwebtoken_jjwt-impl: jjwt-impl 0.12.6
			io_netty_netty-codec-http: netty-codec-http 4.1.112
			net_jodah_expiringmap: expiringmap 0.5.10
			net_lenni0451_commons_httpclient: httpclient 1.5.1
			net_lenni0451_mcping: MCPing 1.4.1
			net_lenni0451_mcstructs-bedrock_forms: forms 1.2.1
			net_lenni0451_mcstructs-bedrock_text: text 1.2.1
			net_raphimc_minecraftauth: MinecraftAuth 4.1.0
			net_raphimc_viaaprilfools-common: viaaprilfools-common 3.0.2-20240821.151113-7
			net_raphimc_viabedrock: ViaBedrock 0.0.11-20240823.131106-5
			net_raphimc_vialegacy: ViaLegacy 3.0.3-20240823.131032-11
			net_raphimc_vialoader: ViaLoader 3.0.3-20240823.130842-14
			org_cloudburstmc_netty_netty-transport-raknet: netty-transport-raknet 1.0.0.CR3-SNAPSHOT
			org_iq80_leveldb_leveldb: leveldb 0.12
			org_iq80_leveldb_leveldb-api: leveldb-api 0.12
			org_lz4_lz4-pure-java: lz4-pure-java 1.8.0
		videotape: Video Tape 1.0.0
		visuality: Visuality 0.7.7+1.21
		vmp: Very Many Players 0.2.0+beta.7.167+1.21.1
		voicechat: Simple Voice Chat 1.21.1-2.5.21
		waveycapes: WaveyCapes 1.4.9
		whereisit: Where Is It 2.6.0+1.21.1
			jackfredlib: JackFredLib 0.10.2+1.21.1
				jackfredlib-base: JackFredLib: Base 1.4.1+1.21.1
				jackfredlib-colour: JackFredLib: Colour 1.1.0+1.21.1
				jackfredlib-extracommandsourcedata: JackFredLib: Extra Command Source Data 1.1.1+1.21.1
				jackfredlib-gps: JackFredLib: GPS 1.0.7+1.21.1
				jackfredlib-lying: JackFredLib: Lying 0.5.5+1.21.1
				jackfredlib-toasts: JackFredLib: Toasts 1.1.1+1.21.1
		word_overflow: Word Overflow 1.0.0
		worldedit: WorldEdit 7.3.6+6892-3d660b8
		xaerominimap: Xaero's Minimap 24.4.0
		xaeroplus: XaeroPlus 2.23.1
			com_github_ben-manes_caffeine_caffeine: caffeine 3.1.8
			net_lenni0451_lambdaevents: LambdaEvents 2.4.2
		xaeroworldmap: Xaero's World Map 1.39.0
		xaerozoomout: XaeroZoomout 2.0.0
		yet_another_config_lib_v3: YetAnotherConfigLib 3.5.0+1.21-fabric
			com_twelvemonkeys_common_common-image: common-image 3.10.0
			com_twelvemonkeys_common_common-io: common-io 3.10.0
			com_twelvemonkeys_common_common-lang: common-lang 3.10.0
			com_twelvemonkeys_imageio_imageio-core: imageio-core 3.10.0
			com_twelvemonkeys_imageio_imageio-metadata: imageio-metadata 3.10.0
			com_twelvemonkeys_imageio_imageio-webp: imageio-webp 3.10.0
			org_quiltmc_parsers_gson: gson 0.2.1
			org_quiltmc_parsers_json: json 0.2.1
		zoomify: Zoomify 2.14.0+1.21
			com_akuleshov7_ktoml-core-jvm: ktoml-core-jvm 0.5.1
```

**Comment by LostLuma** [comment]
Hmm .. the ones that obviously also mess with sound here both seem fine.
I suppose we can just turn the map we're iterating over into a `Concurrent` variant, even if we're not the mod causing this issue.

**Comment by LostLuma** [comment]
Accessing it might be fine, modifying it is def unsafe though.
Either way though, I will just merge the PR I made earlier and release it in an update soonish when I no longer have my fever.

**Comment by LostLuma** [comment]
Well it seems this patch actually caused more issues rather than less, so I will revert it again.
Using [Music Control](https://modrinth.com/mod/music-control) (and maybe other mods) now crashes whenever it queries whether a sound is currently playing.

Since this bug is not caused by Dynamic FPS (everything we do with sound is done on the main thread) I'll keep this closed though.

**Comment by LostLuma** [comment]
Hello, this should now hopefully be properly fixed in `v3.9.2`.
