### ISSUE TITLE
Error with mod menu 4.0.0

### ISSUE THREAD

**Issue by Justsnoopy30** [juliand665/Dynamic-FPS#60]
I noticed this in the logs when opening mod menu with dynamic fps on 1.19.
```
Error from mod 'dynamicfps'
java.lang.IncompatibleClassChangeError: Class net.minecraft.class_2588 does not implement the requested interface net.minecraft.class_2561
	at me.shedaniel.clothconfig2.impl.ConfigBuilderImpl.getOrCreateCategory(ConfigBuilderImpl.java:144)
	at dynamicfps.ClothConfigScreenFactory.genConfig(ClothConfigScreenFactory.java:18)
	at com.terraformersmc.modmenu.ModMenu.getConfigScreen(ModMenu.java:53)
	at com.terraformersmc.modmenu.gui.ModsScreen.method_25426(ModsScreen.java:117)
	at net.minecraft.class_437.method_41843(class_437.java:391)
	at net.minecraft.class_437.method_25423(class_437.java:382)
	at net.minecraft.class_310.method_1507(class_310.java:1001)
	at com.terraformersmc.modmenu.gui.widget.ModMenuButtonWidget.lambda$new$0(ModMenuButtonWidget.java:11)
	at net.minecraft.class_4185.method_25306(class_4185.java:40)
	at net.minecraft.class_4264.method_25348(class_4264.java:16)
	at net.minecraft.class_339.method_25402(class_339.java:120)
	at net.minecraft.class_4069.method_25402(class_4069.java:27)
	at net.minecraft.class_442.method_25402(class_442.java:324)
	at net.minecraft.class_312.method_1611(class_312.java:94)
	at net.minecraft.class_437.method_25412(class_437.java:491)
	at net.minecraft.class_312.method_1601(class_312.java:94)
	at net.minecraft.class_312.method_22686(class_312.java:165)
	at net.minecraft.class_1255.execute(class_1255.java:103)
	at net.minecraft.class_312.method_22684(class_312.java:165)
	at org.lwjgl.glfw.GLFWMouseButtonCallbackI.callback(GLFWMouseButtonCallbackI.java:43)
	at org.lwjgl.system.JNI.invokeV(Native Method)
	at org.lwjgl.glfw.GLFW.glfwWaitEventsTimeout(GLFW.java:3474)
	at com.mojang.blaze3d.systems.RenderSystem.limitDisplayFPS(RenderSystem.java:222)
	at net.minecraft.class_310.method_1523(class_310.java:1174)
	at net.minecraft.class_310.method_1514(class_310.java:734)
	at net.minecraft.client.main.Main.main(Main.java:237)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:460)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
```

**Comment by juliand665** [comment]
Ah damn, looks like updating to 1.19 wasn't as simple as I had hoped. I'll have to take a look. In the meantime, does this make the game crash or does the mod just no longer offer a config screen in Mod Menu?
